Repository mehdiyari/krypt, pull requests merged in 2023-07, with the labels that each got.

#77 Extract backup and restore modules
  app/build.gradle.kts
  app/src/main/java/ir/mehdiyari/krypt/di/modules/RepositoryBindingModule.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/data/DataViewModel.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/restore/RestoreViewModel.kt
  settings.gradle.kts
  shared/cryptography/src/main/java/ir/mehdiyari/krypt/cryptography/utils/Base64Wrapper.kt
  shared/database/build.gradle.kts
  shared/designsystem/theme/src/main/java/ir/mehdiyari/krypt/core/designsystem/theme/Theme.kt
  shared/files/backup-data/build.gradle.kts
  shared/files/backup-logic/.gitignore
  shared/files/backup-logic/build.gradle.kts
  shared/files/backup-logic/src/main/AndroidManifest.xml
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/backup/BackupRepository.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/backup/BackupRepositoryImpl.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/backup/DBBackupModel.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/backup/DBBackupModelJsonAdapter.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/di/BackupModule.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/restore/RestoreRepository.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/restore/RestoreRepositoryImpl.kt
  shared/files/backup-logic/src/test/java/ir/mehdiyari/krypt/backup/logic/backup/BackupRepositoryTest.kt
Labels: Refactor, Modularization

#79 Modularization/extract signup module
  app/build.gradle.kts
  app/src/main/java/ir/mehdiyari/krypt/ui/KryptApp.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/KryptAppState.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/navigation/KryptNavHost.kt
  app/src/main/res/values/strings.xml
  features/auth/create-account/.gitignore
  features/auth/create-account/build.gradle.kts
  features/auth/create-account/src/main/AndroidManifest.xml
  features/auth/create-account/src/main/java/ir/mehdiyari/krypt/features/auth/create_account/CreateAccountComponents.kt
  features/auth/create-account/src/main/java/ir/mehdiyari/krypt/features/auth/create_account/CreateAccountNavigation.kt
  features/auth/create-account/src/main/java/ir/mehdiyari/krypt/features/auth/create_account/CreateAccountRoute.kt
  features/auth/create-account/src/main/java/ir/mehdiyari/krypt/features/auth/create_account/CreateAccountViewModel.kt
  features/auth/create-account/src/main/java/ir/mehdiyari/krypt/features/auth/create_account/CreateAccountViewState.kt
  features/auth/create-account/src/main/res/values/strings.xml
  features/auth/create-account/src/test/java/ir/mehdiyari/krypt/features/auth/create_account/CreateAccountViewModelTest.kt
  settings.gradle.kts
Labels: Improvment, Modularization

#84 Build tool/add features convention plugin
  build-logic/README.md
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  features/auth/create-account/build.gradle.kts
  features/auth/login/build.gradle.kts
  features/settings/build.gradle.kts
Labels: enhancement, Modularization, Build tools

#80 Modularization: Extract backup module
  app/build.gradle.kts
  app/src/main/java/ir/mehdiyari/krypt/ui/KryptApp.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/data/BackupViewData.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/home/Constants.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/media/MediaRoute.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/media/MediasViewModel.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/media/data/EncryptedMediasBucketContentProvider.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/media/data/EncryptedMediasBucketProvider.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/media/data/FalleryBuilderProvider.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/media/player/PlayerViewModel.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/navigation/KryptNavHost.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/text/utils/TextFilesUtils.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/voice/player/MusicPlayerViewModel.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/voice/record/RecordVoiceComponents.kt
  app/src/main/java/ir/mehdiyari/krypt/ui/voice/record/RecordVoiceViewModel.kt
  app/src/main/java/ir/mehdiyari/krypt/utils/Utils.kt
  app/src/main/res/values/strings.xml
  features/backup/.gitignore
  features/backup/build.gradle.kts
  features/backup/src/main/AndroidManifest.xml
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/BackupListComponents.kt
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/BackupViewData.kt
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/BackupViewState.kt
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/DataComponents.kt
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/DataNavigation.kt
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/DataRoute.kt
  features/backup/src/main/java/ir/mehdiyari/krypt/backup/DataViewModel.kt
  features/backup/src/main/res/drawable/ic_backup_24.xml
  features/backup/src/main/res/drawable/ic_backup_file.xml
  features/backup/src/main/res/values/strings.xml
  features/settings/src/main/java/ir/mehdiyari/krypt/setting/data/DeleteAccountHelper.kt
  settings.gradle.kts
  shared/designsystem/components/build.gradle.kts
  shared/designsystem/components/src/main/java/ir/mehdiyari/krypt/shared/designsystem/components/ManageExternalPermissionDialog.kt
  shared/designsystem/resources/src/main/res/drawable/ic_save_as.xml
  shared/designsystem/resources/src/main/res/values/strings.xml
  shared/files/backup-logic/build.gradle.kts
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/backup/BackupRepositoryImpl.kt
  shared/files/backup-logic/src/main/java/ir/mehdiyari/krypt/backup/logic/restore/RestoreRepositoryImpl.kt
  shared/files/backup-logic/src/test/java/ir/mehdiyari/krypt/backup/logic/backup/BackupRepositoryTest.kt
  shared/files/files-logic/src/main/java/ir/mehdiyari/krypt/files/logic/di/FilesModule.kt
  shared/files/files-logic/src/main/java/ir/mehdiyari/krypt/files/logic/repositories/impl/FilesRepositoryImpl.kt
  shared/files/files-logic/src/main/java/ir/mehdiyari/krypt/files/logic/utils/FileWrapper.kt
  shared/files/files-logic/src/main/java/ir/mehdiyari/krypt/files/logic/utils/FilesUtilities.kt
  shared/files/files-logic/src/main/java/ir/mehdiyari/krypt/files/logic/utils/MediaStoreManager.kt
  shared/files/files-logic/src/main/java/ir/mehdiyari/krypt/files/logic/utils/UriUtils.kt
  shared/files/files-logic/src/test/java/ir/mehdiyari/krypt/files/logic/impl/FilesRepositoryTest.kt
  shared/permissions/.gitignore
  shared/permissions/build.gradle.kts
  shared/permissions/src/main/AndroidManifest.xml
  shared/permissions/src/main/java/ir/mehdiyari/krypt/permission/PermissionsHelper.kt
Labels: Modularization
